// <auto-generated />
using AssetRipper.Primitives;
using Il2CppInterop.Runtime.Structs.VersionSpecific.EventInfo;
namespace Il2CppInterop.Runtime.Structs
{
    public static partial class UnityVersionHandler
    {
        private static void SetEventInfoStructHandler(UnityVersion version)
        {
            if (version >= new UnityVersion(2018, 3, 0, UnityVersionType.Alpha, 0))
            {
                EventInfoStructHandler = NativeEventInfoStructHandler_24_0.Instance;
            }
            else if (version >= new UnityVersion(5, 4, 0, UnityVersionType.Beta, 3))
            {
                EventInfoStructHandler = NativeEventInfoStructHandler_19_0.Instance;
            }
            else if (version >= new UnityVersion(5, 4, 0, UnityVersionType.Alpha, 0))
            {
                EventInfoStructHandler = NativeEventInfoStructHandler_16_0.Instance;
            }
            else if (version >= new UnityVersion(5, 3, 1, UnityVersionType.Patch, 3))
            {
                EventInfoStructHandler = NativeEventInfoStructHandler_19_0.Instance;
            }
            else
            {
                EventInfoStructHandler = NativeEventInfoStructHandler_16_0.Instance;
            }
        }
        private static INativeEventInfoStructHandler EventInfoStructHandler { get; set; } = NativeEventInfoStructHandler_16_0.Instance;
    }
}
