// <auto-generated />
namespace Il2CppInterop.Runtime.Structs.VersionSpecific.ParameterInfo
{
    public interface INativeParameterInfoStructHandler : INativeStructHandler
    {
        INativeParameterInfoStruct CreateNewStruct();
        unsafe INativeParameterInfoStruct Wrap(Il2CppParameterInfo* pointer);
    }
    public interface INativeParameterInfoStruct : INativeStruct
    {
        unsafe Il2CppParameterInfo* ParameterInfoPointer { get; }
        bool HasNamePosToken { get; }
        ref nint Name { get; }
        ref int Position { get; }
        ref uint Token { get; }
        unsafe ref Il2CppTypeStruct* ParameterType { get; }
    }
}
