// <auto-generated />
using System.Runtime.InteropServices;
namespace Il2CppInterop.Runtime.Structs.VersionSpecific.ParameterInfo
{
    [ApplicableToUnityVersionsSince("5.2.2")]
    public unsafe class NativeParameterInfoStructHandler_16_0 : INativeParameterInfoStructHandler
    {
        private NativeParameterInfoStructHandler_16_0()
        {
        }
        public INativeParameterInfoStruct CreateNewStruct()
        {
            nint ptr = Marshal.AllocHGlobal(Size);
            Il2CppParameterInfo_16_0* _ = (Il2CppParameterInfo_16_0*)ptr;
            *_ = default;
            return new NativeStructWrapper(ptr);
        }
        public INativeParameterInfoStruct Wrap(Il2CppParameterInfo* ptr)
        {
            if (ptr == null) return null;
            return new NativeStructWrapper((nint)ptr);
        }
        public static NativeParameterInfoStructHandler_16_0 Instance { get; } = new();
        public int Size => sizeof(Il2CppParameterInfo_16_0);
        internal unsafe struct Il2CppParameterInfo_16_0
        {
            public byte* name;
            public int position;
            public uint token;
            public int customAttributeIndex;
            public Il2CppTypeStruct* parameter_type;
        }
        internal class NativeStructWrapper : INativeParameterInfoStruct
        {
            public NativeStructWrapper(nint ptr) => Pointer = ptr;
            public nint Pointer { get; }
            private Il2CppParameterInfo_16_0* _ => (Il2CppParameterInfo_16_0*)Pointer;
            public Il2CppParameterInfo* ParameterInfoPointer => (Il2CppParameterInfo*)Pointer;
            public bool HasNamePosToken => true;
            public ref nint Name => ref *(nint*)&_->name;
            public ref int Position => ref _->position;
            public ref uint Token => ref _->token;
            public ref Il2CppTypeStruct* ParameterType => ref _->parameter_type;
        }
    }
}
