// <auto-generated />
using System.Runtime.InteropServices;
namespace Il2CppInterop.Runtime.Structs.VersionSpecific.ParameterInfo
{
    [ApplicableToUnityVersionsSince("2021.2.0")]
    public unsafe class NativeParameterInfoStructHandler_27_0 : INativeParameterInfoStructHandler
    {
        private NativeParameterInfoStructHandler_27_0()
        {
        }
        public INativeParameterInfoStruct CreateNewStruct()
        {
            nint ptr = Marshal.AllocHGlobal(Size);
            Il2CppParameterInfo_27_0* _ = (Il2CppParameterInfo_27_0*)ptr;
            *_ = default;
            return new NativeStructWrapper(ptr);
        }
        public INativeParameterInfoStruct Wrap(Il2CppParameterInfo* ptr)
        {
            if (ptr == null) return null;
            return new NativeStructWrapper((nint)ptr);
        }
        public static NativeParameterInfoStructHandler_27_0 Instance { get; } = new();
        public int Size => sizeof(Il2CppParameterInfo_27_0);
        internal unsafe struct Il2CppParameterInfo_27_0
        {
            public Il2CppTypeStruct* parameter_type;
        }
        internal class NativeStructWrapper : INativeParameterInfoStruct
        {
            public NativeStructWrapper(nint ptr) => Pointer = ptr;
            public nint Pointer { get; }
            private Il2CppParameterInfo_27_0* _ => (Il2CppParameterInfo_27_0*)Pointer;
            public Il2CppParameterInfo* ParameterInfoPointer => (Il2CppParameterInfo*)Pointer;
            public bool HasNamePosToken => false;
            public ref nint Name => throw new System.NotSupportedException();
            public ref int Position => throw new System.NotSupportedException();
            public ref uint Token => throw new System.NotSupportedException();
            public ref Il2CppTypeStruct* ParameterType => ref _->parameter_type;
        }
    }
}
