// <auto-generated />
using AssetRipper.Primitives;
using Il2CppInterop.Runtime.Structs.VersionSpecific.ParameterInfo;
namespace Il2CppInterop.Runtime.Structs
{
    public static partial class UnityVersionHandler
    {
        private static void SetParameterInfoStructHandler(UnityVersion version)
        {
            if (version >= new UnityVersion(2021, 2, 0, UnityVersionType.Alpha, 0))
            {
                ParameterInfoStructHandler = NativeParameterInfoStructHandler_27_0.Instance;
            }
            else if (version >= new UnityVersion(2018, 3, 0, UnityVersionType.Alpha, 0))
            {
                ParameterInfoStructHandler = NativeParameterInfoStructHandler_24_0.Instance;
            }
            else
            {
                ParameterInfoStructHandler = NativeParameterInfoStructHandler_16_0.Instance;
            }
        }
        private static INativeParameterInfoStructHandler ParameterInfoStructHandler { get; set; } = NativeParameterInfoStructHandler_16_0.Instance;
    }
}
