// <auto-generated />
using System.Runtime.InteropServices;
namespace Il2CppInterop.Runtime.Structs.VersionSpecific.AssemblyName
{
    [ApplicableToUnityVersionsSince("2018.4.34")]
    [ApplicableToUnityVersionsSince("2019.4.15")]
    [ApplicableToUnityVersionsSince("2020.1.11")]
    [ApplicableToUnityVersionsSince("2020.2.0b7")]
    public unsafe class NativeAssemblyNameStructHandler_24_1 : INativeAssemblyNameStructHandler
    {
        private NativeAssemblyNameStructHandler_24_1()
        {
        }
        public INativeAssemblyNameStruct CreateNewStruct()
        {
            nint ptr = Marshal.AllocHGlobal(Size);
            Il2CppAssemblyName_24_1* _ = (Il2CppAssemblyName_24_1*)ptr;
            *_ = default;
            return new NativeStructWrapper(ptr);
        }
        public INativeAssemblyNameStruct Wrap(Il2CppAssemblyName* ptr)
        {
            if (ptr == null) return null;
            return new NativeStructWrapper((nint)ptr);
        }
        public static NativeAssemblyNameStructHandler_24_1 Instance { get; } = new();
        public int Size => sizeof(Il2CppAssemblyName_24_1);
        internal unsafe struct Il2CppAssemblyName_24_1
        {
            public byte* name;
            public byte* culture;
            public byte* public_key;
            public uint hash_alg;
            public int hash_len;
            public uint flags;
            public int major;
            public int minor;
            public int build;
            public int revision;
            public ulong public_key_token;
        }
        internal class NativeStructWrapper : INativeAssemblyNameStruct
        {
            public NativeStructWrapper(nint ptr) => Pointer = ptr;
            public nint Pointer { get; }
            private Il2CppAssemblyName_24_1* _ => (Il2CppAssemblyName_24_1*)Pointer;
            public Il2CppAssemblyName* AssemblyNamePointer => (Il2CppAssemblyName*)Pointer;
            public ref nint Name => ref *(nint*)&_->name;
            public ref nint Culture => ref *(nint*)&_->culture;
            public ref nint PublicKey => ref *(nint*)&_->public_key;
            public ref int Major => ref _->major;
            public ref int Minor => ref _->minor;
            public ref int Build => ref _->build;
            public ref int Revision => ref _->revision;
            public ref ulong PublicKeyToken => ref _->public_key_token;
        }
    }
}
