// <auto-generated />
namespace Il2CppInterop.Runtime.Structs.VersionSpecific.AssemblyName
{
    public interface INativeAssemblyNameStructHandler : INativeStructHandler
    {
        INativeAssemblyNameStruct CreateNewStruct();
        unsafe INativeAssemblyNameStruct Wrap(Il2CppAssemblyName* pointer);
    }
    public interface INativeAssemblyNameStruct : INativeStruct
    {
        unsafe Il2CppAssemblyName* AssemblyNamePointer { get; }
        ref nint Name { get; }
        ref nint Culture { get; }
        ref nint PublicKey { get; }
        ref int Major { get; }
        ref int Minor { get; }
        ref int Build { get; }
        ref int Revision { get; }
        ref ulong PublicKeyToken { get; }
    }
}
