// <auto-generated />
using AssetRipper.Primitives;
using Il2CppInterop.Runtime.Structs.VersionSpecific.AssemblyName;
namespace Il2CppInterop.Runtime.Structs
{
    public static partial class UnityVersionHandler
    {
        private static void SetAssemblyNameStructHandler(UnityVersion version)
        {
            if (version >= new UnityVersion(2020, 2, 0, UnityVersionType.Beta, 7))
            {
                AssemblyNameStructHandler = NativeAssemblyNameStructHandler_24_1.Instance;
            }
            else if (version >= new UnityVersion(2020, 2, 0, UnityVersionType.Alpha, 0))
            {
                AssemblyNameStructHandler = NativeAssemblyNameStructHandler_24_0.Instance;
            }
            else if (version >= new UnityVersion(2020, 1, 11, UnityVersionType.Alpha, 0))
            {
                AssemblyNameStructHandler = NativeAssemblyNameStructHandler_24_1.Instance;
            }
            else if (version >= new UnityVersion(2020, 1, 0, UnityVersionType.Alpha, 0))
            {
                AssemblyNameStructHandler = NativeAssemblyNameStructHandler_24_0.Instance;
            }
            else if (version >= new UnityVersion(2019, 4, 15, UnityVersionType.Alpha, 0))
            {
                AssemblyNameStructHandler = NativeAssemblyNameStructHandler_24_1.Instance;
            }
            else if (version >= new UnityVersion(2019, 1, 0, UnityVersionType.Alpha, 0))
            {
                AssemblyNameStructHandler = NativeAssemblyNameStructHandler_24_0.Instance;
            }
            else if (version >= new UnityVersion(2018, 4, 34, UnityVersionType.Alpha, 0))
            {
                AssemblyNameStructHandler = NativeAssemblyNameStructHandler_24_1.Instance;
            }
            else if (version >= new UnityVersion(2018, 1, 0, UnityVersionType.Beta, 5))
            {
                AssemblyNameStructHandler = NativeAssemblyNameStructHandler_24_0.Instance;
            }
            else
            {
                AssemblyNameStructHandler = NativeAssemblyNameStructHandler_16_0.Instance;
            }
        }
        private static INativeAssemblyNameStructHandler AssemblyNameStructHandler { get; set; } = NativeAssemblyNameStructHandler_16_0.Instance;
    }
}
