// <auto-generated />
using System.Runtime.InteropServices;
namespace Il2CppInterop.Runtime.Structs.VersionSpecific.FieldInfo
{
    [ApplicableToUnityVersionsSince("5.2.2")]
    [ApplicableToUnityVersionsSince("5.4.0")]
    public unsafe class NativeFieldInfoStructHandler_16_0 : INativeFieldInfoStructHandler
    {
        private NativeFieldInfoStructHandler_16_0()
        {
        }
        public INativeFieldInfoStruct CreateNewStruct()
        {
            nint ptr = Marshal.AllocHGlobal(Size);
            Il2CppFieldInfo_16_0* _ = (Il2CppFieldInfo_16_0*)ptr;
            *_ = default;
            return new NativeStructWrapper(ptr);
        }
        public INativeFieldInfoStruct Wrap(Il2CppFieldInfo* ptr)
        {
            if (ptr == null) return null;
            return new NativeStructWrapper((nint)ptr);
        }
        public static NativeFieldInfoStructHandler_16_0 Instance { get; } = new();
        public int Size => sizeof(Il2CppFieldInfo_16_0);
        internal unsafe struct Il2CppFieldInfo_16_0
        {
            public byte* name;
            public Il2CppTypeStruct* type;
            public Il2CppClass* parent;
            public int offset;
            public int customAttributeIndex;
        }
        internal class NativeStructWrapper : INativeFieldInfoStruct
        {
            public NativeStructWrapper(nint ptr) => Pointer = ptr;
            public nint Pointer { get; }
            private Il2CppFieldInfo_16_0* _ => (Il2CppFieldInfo_16_0*)Pointer;
            public Il2CppFieldInfo* FieldInfoPointer => (Il2CppFieldInfo*)Pointer;
            public ref nint Name => ref *(nint*)&_->name;
            public ref Il2CppTypeStruct* Type => ref _->type;
            public ref Il2CppClass* Parent => ref _->parent;
            public ref int Offset => ref _->offset;
        }
    }
}
