// <auto-generated />
using AssetRipper.Primitives;
using Il2CppInterop.Runtime.Structs.VersionSpecific.FieldInfo;
namespace Il2CppInterop.Runtime.Structs
{
    public static partial class UnityVersionHandler
    {
        private static void SetFieldInfoStructHandler(UnityVersion version)
        {
            if (version >= new UnityVersion(2018, 3, 0, UnityVersionType.Alpha, 0))
            {
                FieldInfoStructHandler = NativeFieldInfoStructHandler_24_0.Instance;
            }
            else if (version >= new UnityVersion(5, 4, 0, UnityVersionType.Beta, 3))
            {
                FieldInfoStructHandler = NativeFieldInfoStructHandler_19_0.Instance;
            }
            else if (version >= new UnityVersion(5, 4, 0, UnityVersionType.Alpha, 0))
            {
                FieldInfoStructHandler = NativeFieldInfoStructHandler_16_0.Instance;
            }
            else if (version >= new UnityVersion(5, 3, 1, UnityVersionType.Patch, 3))
            {
                FieldInfoStructHandler = NativeFieldInfoStructHandler_19_0.Instance;
            }
            else
            {
                FieldInfoStructHandler = NativeFieldInfoStructHandler_16_0.Instance;
            }
        }
        private static INativeFieldInfoStructHandler FieldInfoStructHandler { get; set; } = NativeFieldInfoStructHandler_16_0.Instance;
    }
}
