// <auto-generated />
namespace Il2CppInterop.Runtime.Structs.VersionSpecific.MethodInfo
{
    public interface INativeMethodInfoStructHandler : INativeStructHandler
    {
        INativeMethodInfoStruct CreateNewStruct();
        unsafe INativeMethodInfoStruct Wrap(Il2CppMethodInfo* pointer);
    }
    public interface INativeMethodInfoStruct : INativeStruct
    {
        unsafe Il2CppMethodInfo* MethodInfoPointer { get; }
        ref nint Name { get; }
        ref ushort Slot { get; }
        ref nint MethodPointer { get; }
        ref nint VirtualMethodPointer { get; }
        unsafe ref Il2CppClass* Class { get; }
        ref nint InvokerMethod { get; }
        unsafe ref Il2CppTypeStruct* ReturnType { get; }
        ref Il2CppMethodFlags Flags { get; }
        ref byte ParametersCount { get; }
        unsafe ref Il2CppParameterInfo* Parameters { get; }
        ref uint Token { get; }
        bool IsGeneric { get; set; }
        bool IsInflated { get; set; }
        bool IsMarshalledFromNative { get; set; }
    }
}
