// <auto-generated />
using AssetRipper.Primitives;
using Il2CppInterop.Runtime.Structs.VersionSpecific.MethodInfo;
namespace Il2CppInterop.Runtime.Structs
{
    public static partial class UnityVersionHandler
    {
        private static void SetMethodInfoStructHandler(UnityVersion version)
        {
            if (version >= new UnityVersion(2023, 2, 0, UnityVersionType.Alpha, 22))
            {
                MethodInfoStructHandler = NativeMethodInfoStructHandler_29_2.Instance;
            }
            else if (version >= new UnityVersion(2022, 1, 0, UnityVersionType.Beta, 7))
            {
                MethodInfoStructHandler = NativeMethodInfoStructHandler_29_0.Instance;
            }
            else if (version >= new UnityVersion(2022, 1, 0, UnityVersionType.Alpha, 10))
            {
                MethodInfoStructHandler = NativeMethodInfoStructHandler_29_1.Instance;
            }
            else if (version >= new UnityVersion(2022, 1, 0, UnityVersionType.Alpha, 0))
            {
                MethodInfoStructHandler = NativeMethodInfoStructHandler_29_0.Instance;
            }
            else if (version >= new UnityVersion(2021, 2, 0, UnityVersionType.Beta, 13))
            {
                MethodInfoStructHandler = NativeMethodInfoStructHandler_29_1.Instance;
            }
            else if (version >= new UnityVersion(2021, 2, 0, UnityVersionType.Beta, 8))
            {
                MethodInfoStructHandler = NativeMethodInfoStructHandler_29_0.Instance;
            }
            else if (version >= new UnityVersion(2021, 2, 0, UnityVersionType.Beta, 7))
            {
                MethodInfoStructHandler = NativeMethodInfoStructHandler_28_0.Instance;
            }
            else if (version >= new UnityVersion(2021, 2, 0, UnityVersionType.Alpha, 0))
            {
                MethodInfoStructHandler = NativeMethodInfoStructHandler_27_0.Instance;
            }
            else if (version >= new UnityVersion(2018, 3, 0, UnityVersionType.Alpha, 0))
            {
                MethodInfoStructHandler = NativeMethodInfoStructHandler_24_2.Instance;
            }
            else if (version >= new UnityVersion(2018, 1, 0, UnityVersionType.Final, 1))
            {
                MethodInfoStructHandler = NativeMethodInfoStructHandler_24_1.Instance;
            }
            else if (version >= new UnityVersion(2018, 1, 0, UnityVersionType.Beta, 5))
            {
                MethodInfoStructHandler = NativeMethodInfoStructHandler_24_0.Instance;
            }
            else if (version >= new UnityVersion(5, 4, 0, UnityVersionType.Beta, 22))
            {
                MethodInfoStructHandler = NativeMethodInfoStructHandler_21_0.Instance;
            }
            else if (version >= new UnityVersion(5, 4, 0, UnityVersionType.Alpha, 0))
            {
                MethodInfoStructHandler = NativeMethodInfoStructHandler_16_0.Instance;
            }
            else if (version >= new UnityVersion(5, 3, 5, UnityVersionType.Patch, 3))
            {
                MethodInfoStructHandler = NativeMethodInfoStructHandler_21_0.Instance;
            }
            else
            {
                MethodInfoStructHandler = NativeMethodInfoStructHandler_16_0.Instance;
            }
        }
        private static INativeMethodInfoStructHandler MethodInfoStructHandler { get; set; } = NativeMethodInfoStructHandler_16_0.Instance;
    }
}
