using System.CodeDom.Compiler;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Il2CppInterop.SourceGenerator;

[Generator]
public sealed class InjectedTypeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var types = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Il2CppInterop.Common.Attributes.InjectedTypeAttribute",
                predicate: static (node, _) =>
                {
                    if (node is not TypeDeclarationSyntax tds)
                        return false;
                    if (!tds.Modifiers.Any(SyntaxKind.PartialKeyword))
                        return false;
                    // Type must be non-generic
                    return tds switch
                    {
                        ClassDeclarationSyntax s => s.TypeParameterList is null,
                        InterfaceDeclarationSyntax s => s.TypeParameterList is null,
                        StructDeclarationSyntax s => s.TypeParameterList is null,
                        _ => false,
                    };
                },
                transform: static (ctx, ct) =>
                {

                    var injectedTypeAttr = ctx.Attributes[0];
                    var @namespace = injectedTypeAttr.NamedArguments
                        .FirstOrDefault(a => a.Key == "Namespace")
                        .Value.Value as string;
                    var name = injectedTypeAttr.NamedArguments
                        .FirstOrDefault(a => a.Key == "Name")
                        .Value.Value as string;
                    return TypeModel.FromSymbol((INamedTypeSymbol)ctx.TargetSymbol, @namespace, name, ct);
                })
            .Where(static m => m is not null);

        context.RegisterSourceOutput(types, static (ctx, model) => Emit(ctx, model!));
    }


    private static void Emit(SourceProductionContext ctx, TypeModel model)
    {
        using var sw = new StringWriter()
        {
            NewLine = "\n"
        };
        using var writer = new IndentedTextWriter(sw, "    ");

        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            writer.WriteLine($"namespace {model.Namespace}");
            writer.WriteLine("{");
            writer.Indent++;
        }

        EmitPartialType(writer, model);
        writer.WriteLineNoTabs();
        EmitInternalsClass(writer, model);

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            writer.Indent--;
            writer.WriteLine("}");
        }

        var hint = string.IsNullOrEmpty(model.Namespace)
            ? $"{model.TypeName}.g.cs"
            : $"{model.Namespace}.{model.TypeName}.g.cs";

        ctx.AddSource(hint, sw.ToString());
    }

    private static void EmitPartialType(IndentedTextWriter writer, TypeModel model)
    {
        var access = model.DeclaredAccessibility?.GetAccessibilityKeyword();

        writer.Write("[global::Il2CppInterop.Common.Attributes.Il2CppType(typeof(Il2CppInternals)");
        if (model.Il2CppNamespace is not null && !string.Equals(model.Il2CppNamespace, model.Namespace, StringComparison.Ordinal))
        {
            writer.Write($", Namespace = {SymbolDisplay.FormatLiteral(model.Il2CppNamespace, true)}");
        }
        if (model.Il2CppName is not null && !string.Equals(model.Il2CppName, model.TypeName, StringComparison.Ordinal))
        {
            writer.Write($", Name = {SymbolDisplay.FormatLiteral(model.Il2CppName, true)}");
        }
        writer.WriteLine(")]");

        if (model.TypeKind == TypeKind.Struct)
        {
            writer.WriteLine($"{access} partial struct {model.TypeName} :");
            writer.Indent++;
            writer.WriteLine("global::Il2CppSystem.IValueType,");
            writer.WriteLine($"global::Il2CppInterop.Common.IIl2CppType<{model.TypeName}>");
            writer.Indent--;
        }
        else
        {
            writer.WriteLine($"{access} partial {model.TypeKind.GetTypeKeyword()} {model.TypeName} : global::Il2CppInterop.Common.IIl2CppType<{model.TypeName}>");
        }

        writer.WriteLine("{");
        writer.Indent++;

        if (model.TypeKind == TypeKind.Struct)
        {
            EmitValueTypeBridgeMethods(writer);
            writer.WriteLineNoTabs();
        }
        foreach (var member in model.Members)
        {
            if (member.IsStatic)
            {
                EmitStaticIl2CppProperty(writer, member);
            }
            else if (model.TypeKind == TypeKind.Struct)
            {
                // It is an error to use [Il2CppField] on an instance property of a value type.
                continue;
            }
            else if (member.Kind == MemberKind.Il2Cpp)
            {
                EmitIl2CppProperty(writer, member);
            }
            else
            {
                EmitManagedProperty(writer, member);
            }

            writer.WriteLineNoTabs();
        }
        if (model.NeedsObjectPointerConstructor)
        {
            EmitConstructor(writer, model);
            writer.WriteLineNoTabs();
        }

        if (model.FinalizerMethodNames.Count > 0 || model.Members.Any(m => m.Kind == MemberKind.Managed))
        {
            EmitFinalizer(writer, model);
            writer.WriteLineNoTabs();
            EmitLogErrorFinalizer(writer);
            writer.WriteLineNoTabs();
        }

        EmitInterfaceMembers(writer, model);

        writer.Indent--;
        writer.WriteLine("}");
    }

    #region Value-type-only emit

    private static void EmitValueTypeBridgeMethods(IndentedTextWriter writer)
    {
        writer.WriteLine("[global::Il2CppInterop.Common.Attributes.Il2CppMethod]");
        writer.WriteLine("public global::Il2CppSystem.Boolean Equals(global::Il2CppSystem.IObject obj)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("return this.Equals((object)obj);");
        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLineNoTabs();

        writer.WriteLine("[global::Il2CppInterop.Common.Attributes.Il2CppMethod(Name = \"GetHashCode\")]");
        writer.WriteLine("public global::Il2CppSystem.Int32 GetIl2CppHashCode()");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("return this.GetHashCode();");
        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLineNoTabs();

        writer.WriteLine("[global::Il2CppInterop.Common.Attributes.Il2CppMethod(Name = \"ToString\")]");
        writer.WriteLine("public global::Il2CppSystem.String ToIl2CppString()");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("return this.ToString();");
        writer.Indent--;
        writer.WriteLine("}");
    }

    #endregion

    #region Class/interface-only emit

    private static void EmitStaticIl2CppProperty(IndentedTextWriter writer, MemberModel member)
    {
        var accessPrefix = member.Accessibility is { } a ? a.GetAccessibilityKeyword() + " " : "";
        writer.WriteLine($"{accessPrefix}static partial {member.Type} {member.Name}");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine($"get => global::Il2CppInterop.Runtime.FieldAccess.GetStaticFieldValue<{member.Type}>(Il2CppInternals.FieldInfoPtr_{member.Index});");
        writer.WriteLine($"set => global::Il2CppInterop.Runtime.FieldAccess.SetStaticFieldValue(Il2CppInternals.FieldInfoPtr_{member.Index}, value);");
        writer.Indent--;
        writer.WriteLine("}");
    }

    private static void EmitIl2CppProperty(IndentedTextWriter writer, MemberModel member)
    {
        var accessPrefix = member.Accessibility is { } a ? a.GetAccessibilityKeyword() + " " : "";
        writer.WriteLine($"{accessPrefix}partial {member.Type} {member.Name}");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine($"get => global::Il2CppInterop.Runtime.FieldAccess.GetInstanceFieldValue<{member.Type}>(this, Il2CppInternals.FieldOffset_{member.Index});");
        writer.WriteLine($"set => global::Il2CppInterop.Runtime.FieldAccess.SetInstanceFieldValue(this, Il2CppInternals.FieldOffset_{member.Index}, value);");
        writer.Indent--;
        writer.WriteLine("}");
    }

    private static void EmitManagedProperty(IndentedTextWriter writer, MemberModel member)
    {
        // Backing field
        writer.WriteLine($"[global::Il2CppInterop.Common.Attributes.Il2CppField(Name = nameof({member.Name}))]");
        writer.WriteLine($"private global::Il2CppSystem.IntPtr {member.Name}__BackingField");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine($"get => global::Il2CppInterop.Runtime.FieldAccess.GetInstanceFieldValue<global::Il2CppSystem.IntPtr>(this, Il2CppInternals.FieldOffset_{member.Index});");
        writer.WriteLine($"set => global::Il2CppInterop.Runtime.FieldAccess.SetInstanceFieldValue(this, Il2CppInternals.FieldOffset_{member.Index}, value);");
        writer.Indent--;
        writer.WriteLine("}");

        writer.WriteLineNoTabs();

        // Public partial property
        var accessPrefix = member.Accessibility is { } a ? a.GetAccessibilityKeyword() + " " : "";
        writer.WriteLine($"{accessPrefix}partial {member.Type} {member.Name}");
        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine($"get => global::System.Runtime.InteropServices.GCHandle<{member.Type}>.FromIntPtr({member.Name}__BackingField).Target;");

        writer.WriteLine("set");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine($"global::System.Runtime.InteropServices.GCHandle<{member.Type}>.FromIntPtr({member.Name}__BackingField).Dispose();");
        writer.WriteLine($"{member.Name}__BackingField = value is not null");
        writer.Indent++;
        writer.WriteLine($"? global::System.Runtime.InteropServices.GCHandle<{member.Type}>.ToIntPtr(new global::System.Runtime.InteropServices.GCHandle<{member.Type}>(value))");
        writer.WriteLine(": default;");
        writer.Indent--;
        writer.Indent--;
        writer.WriteLine("}");

        writer.Indent--;
        writer.WriteLine("}");
    }

    private static void EmitConstructor(IndentedTextWriter writer, TypeModel model)
    {
        writer.WriteLine($"public {model.TypeName}(global::Il2CppInterop.Common.ObjectPointer pointer) : base(pointer)");
        writer.WriteLine("{");
        writer.WriteLine("}");
    }

    private static void EmitFinalizer(IndentedTextWriter writer, TypeModel model)
    {
        writer.WriteLine("[global::Il2CppInterop.Common.Attributes.Il2CppMethod(Name = \"Finalize\")]");
        writer.WriteLine("public override void Il2CppFinalize()");
        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("// This disposal happens when the object is collected by the Il2Cpp GC instead of the managed GC.");
        writer.WriteLine("// That ensures that the referenced value is kept alive as long as the Il2Cpp object is alive, even if the managed wrapper gets collected.");
        writer.WriteLine("// In theory, the managed wrapper could be collected and recreated multiple times during the lifetime of the Il2Cpp object,");
        writer.WriteLine("// so this ensures that the managed fields are not disposed prematurely.");

        writer.WriteLine("try");
        writer.WriteLine("{");
        writer.Indent++;

        foreach (var name in model.FinalizerMethodNames)
            writer.WriteLine($"this.{name}();");

        foreach (var f in model.Members.Where(f => f.Kind == MemberKind.Managed))
            writer.WriteLine($"{f.Name} = null!;");

        writer.Indent--;
        writer.WriteLine("}");

        writer.WriteLine("catch (global::System.Exception ex)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("LogErrorIl2CppFinalize(ex);");
        writer.Indent--;
        writer.WriteLine("}");

        writer.WriteLine("finally");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("base.Il2CppFinalize(); // Must call base method");
        writer.Indent--;
        writer.WriteLine("}");

        writer.Indent--;
        writer.WriteLine("}");
    }

    private static void EmitLogErrorFinalizer(IndentedTextWriter writer)
    {
        writer.WriteLine("partial void LogErrorIl2CppFinalize(global::System.Exception exception);");
    }

    #endregion

    #region Shared emit

    private static void EmitInterfaceMembers(IndentedTextWriter writer, TypeModel model)
    {
        var typeName = model.TypeName;

        // ObjectClass
        writer.WriteLine($"nint global::Il2CppInterop.Common.IIl2CppType.ObjectClass => global::Il2CppInterop.Common.Il2CppType.GetClassPointer<{typeName}>();");
        writer.WriteLineNoTabs();

        if (model.TypeKind == TypeKind.Struct)
        {
            // BoxNative
            writer.WriteLine($"readonly global::Il2CppInterop.Common.ObjectPointer global::Il2CppInterop.Common.IIl2CppType.BoxNative() => global::Il2CppInterop.Runtime.NativeBoxing.BoxValueType<{typeName}>(in this);");
            writer.WriteLineNoTabs();

            // Size
            writer.WriteLine($"static int global::Il2CppInterop.Common.IIl2CppType<{typeName}>.Size => Il2CppInternals.Size;");
            writer.WriteLineNoTabs();

            // ReadFromSpan — constructs via object initializer, one field per offset
            writer.WriteLine($"static {typeName} global::Il2CppInterop.Common.IIl2CppType<{typeName}>.ReadFromSpan(global::System.ReadOnlySpan<byte> span)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("#nullable disable");
            writer.WriteLine($"return new {typeName}");
            writer.WriteLine("{");
            writer.Indent++;
            foreach (var member in model.Members.Where(x => !x.IsStatic))
                writer.WriteLine($"{member.Name} = global::Il2CppInterop.Common.Il2CppType.ReadFromSpanAtOffset<{member.Type}>(span, Il2CppInternals.FieldOffset_{member.Index}),");
            writer.Indent--;
            writer.WriteLine("};");
            writer.WriteLine("#nullable restore");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLineNoTabs();

            // WriteToSpan — one WriteToSpanAtOffset call per field
            writer.WriteLine($"static void global::Il2CppInterop.Common.IIl2CppType<{typeName}>.WriteToSpan({typeName} value, global::System.Span<byte> span)");
            writer.WriteLine("{");
            writer.Indent++;
            foreach (var member in model.Members.Where(x => !x.IsStatic))
                writer.WriteLine($"global::Il2CppInterop.Common.Il2CppType.WriteToSpanAtOffset(value.{member.Name}, span, Il2CppInternals.FieldOffset_{member.Index});");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLineNoTabs();
        }
        else
        {
            // UnboxNative
            writer.WriteLine($"static {typeName} global::Il2CppInterop.Common.IIl2CppType<{typeName}>.UnboxNative(global::Il2CppInterop.Common.ObjectPointer pointer) => new {typeName}(pointer);");
            writer.WriteLineNoTabs();

            // Size
            writer.WriteLine($"static int global::Il2CppInterop.Common.IIl2CppType<{typeName}>.Size => nint.Size;");
            writer.WriteLineNoTabs();

            // ReadFromSpan
            writer.WriteLine($"static {typeName}? global::Il2CppInterop.Common.IIl2CppType<{typeName}>.ReadFromSpan(global::System.ReadOnlySpan<byte> span)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"return global::Il2CppInterop.Common.Il2CppType.ReadReference<{typeName}>(span);");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLineNoTabs();

            // WriteToSpan
            writer.WriteLine($"static void global::Il2CppInterop.Common.IIl2CppType<{typeName}>.WriteToSpan({typeName}? value, global::System.Span<byte> span)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("global::Il2CppInterop.Common.Il2CppType.WriteReference(value, span);");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLineNoTabs();
        }

        writer.WriteLine($"static {typeName}()");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("global::System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(typeof(Il2CppInternals).TypeHandle);");
        writer.Indent--;
        writer.WriteLine("}");
    }

    private static void EmitInternalsClass(IndentedTextWriter writer, TypeModel model)
    {
        var isValueType = model.TypeKind == TypeKind.Struct;

        writer.WriteLine("file static class Il2CppInternals");
        writer.WriteLine("{");
        writer.Indent++;

        if (isValueType)
        {
            writer.WriteLine("public static readonly int Size;");
        }
        foreach (var member in model.Members)
        {
            if (member.IsStatic)
                writer.WriteLine($"public static readonly nint FieldInfoPtr_{member.Index}; // {member.Name}");
            else
                writer.WriteLine($"public static readonly int FieldOffset_{member.Index}; // {member.Name}");
        }
        writer.WriteLineNoTabs();
        writer.WriteLine("static Il2CppInternals()");
        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLineNoTabs("#pragma warning disable IL2026 // Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code");
        writer.WriteLineNoTabs("#pragma warning disable IL3050 // Calling members annotated with 'RequiresDynamicCodeAttribute' may break functionality when AOT compiling.");
        writer.WriteLine($"global::Il2CppInterop.Runtime.Injection.TypeInjector.RegisterTypeInIl2Cpp<{model.TypeName}>();");
        writer.WriteLineNoTabs("#pragma warning restore IL3050 // Calling members annotated with 'RequiresDynamicCodeAttribute' may break functionality when AOT compiling.");
        writer.WriteLineNoTabs("#pragma warning restore IL2026 // Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code");

        if (isValueType)
        {
            writer.WriteLine($"Size = global::Il2CppInterop.Common.IL2CPP.il2cpp_class_value_size(global::Il2CppInterop.Common.Il2CppType.GetClassPointer<{model.TypeName}>(), out _);");
        }

        foreach (var member in model.Members)
        {
            if (member.IsStatic)
                writer.WriteLine($"FieldInfoPtr_{member.Index} = global::Il2CppInterop.Runtime.FieldAccess.GetFieldInfo(global::Il2CppInterop.Common.Il2CppType.GetClassPointer<{model.TypeName}>(), \"{member.Name}\");");
            else
                writer.WriteLine($"FieldOffset_{member.Index} = global::Il2CppInterop.Runtime.FieldAccess.GetFieldOffset(global::Il2CppInterop.Runtime.FieldAccess.GetFieldInfo(global::Il2CppInterop.Common.Il2CppType.GetClassPointer<{model.TypeName}>(), \"{member.Name}\"));");
        }

        writer.Indent--;
        writer.WriteLine("}");

        writer.Indent--;
        writer.WriteLine("}");
    }
    #endregion
}
