// <auto-generated />
using System.Runtime.InteropServices;
namespace Il2CppInterop.Runtime.Structs.VersionSpecific.PropertyInfo
{
    [ApplicableToUnityVersionsSince("5.3.1p3")]
    [ApplicableToUnityVersionsSince("5.4.0b3")]
    public unsafe class NativePropertyInfoStructHandler_19_0 : INativePropertyInfoStructHandler
    {
        private NativePropertyInfoStructHandler_19_0()
        {
        }
        public INativePropertyInfoStruct CreateNewStruct()
        {
            nint ptr = Marshal.AllocHGlobal(Size);
            Il2CppPropertyInfo_19_0* _ = (Il2CppPropertyInfo_19_0*)ptr;
            *_ = default;
            return new NativeStructWrapper(ptr);
        }
        public INativePropertyInfoStruct Wrap(Il2CppPropertyInfo* ptr)
        {
            if (ptr == null) return null;
            return new NativeStructWrapper((nint)ptr);
        }
        public static NativePropertyInfoStructHandler_19_0 Instance { get; } = new();
        public int Size => sizeof(Il2CppPropertyInfo_19_0);
        internal unsafe struct Il2CppPropertyInfo_19_0
        {
            public Il2CppClass* parent;
            public byte* name;
            public Il2CppMethodInfo* get;
            public Il2CppMethodInfo* set;
            public uint attrs;
            public int customAttributeIndex;
            public uint token;
        }
        internal class NativeStructWrapper : INativePropertyInfoStruct
        {
            public NativeStructWrapper(nint ptr) => Pointer = ptr;
            public nint Pointer { get; }
            private Il2CppPropertyInfo_19_0* _ => (Il2CppPropertyInfo_19_0*)Pointer;
            public Il2CppPropertyInfo* PropertyInfoPointer => (Il2CppPropertyInfo*)Pointer;
            public ref nint Name => ref *(nint*)&_->name;
            public ref Il2CppClass* Parent => ref _->parent;
            public ref Il2CppMethodInfo* Get => ref _->get;
            public ref Il2CppMethodInfo* Set => ref _->set;
            public ref uint Attrs => ref _->attrs;
        }
    }
}
