// <auto-generated />
using AssetRipper.Primitives;
using Il2CppInterop.Runtime.Structs.VersionSpecific.PropertyInfo;
namespace Il2CppInterop.Runtime.Structs
{
    public static partial class UnityVersionHandler
    {
        private static void SetPropertyInfoStructHandler(UnityVersion version)
        {
            if (version >= new UnityVersion(2018, 3, 0, UnityVersionType.Alpha, 0))
            {
                PropertyInfoStructHandler = NativePropertyInfoStructHandler_24_0.Instance;
            }
            else if (version >= new UnityVersion(5, 4, 0, UnityVersionType.Beta, 3))
            {
                PropertyInfoStructHandler = NativePropertyInfoStructHandler_19_0.Instance;
            }
            else if (version >= new UnityVersion(5, 4, 0, UnityVersionType.Alpha, 0))
            {
                PropertyInfoStructHandler = NativePropertyInfoStructHandler_16_0.Instance;
            }
            else if (version >= new UnityVersion(5, 3, 1, UnityVersionType.Patch, 3))
            {
                PropertyInfoStructHandler = NativePropertyInfoStructHandler_19_0.Instance;
            }
            else
            {
                PropertyInfoStructHandler = NativePropertyInfoStructHandler_16_0.Instance;
            }
        }
        private static INativePropertyInfoStructHandler PropertyInfoStructHandler { get; set; } = NativePropertyInfoStructHandler_16_0.Instance;
    }
}
