// <auto-generated />
using AssetRipper.Primitives;
using Il2CppInterop.Runtime.Structs.VersionSpecific.Class;
namespace Il2CppInterop.Runtime.Structs
{
    public static partial class UnityVersionHandler
    {
        private static void SetClassStructHandler(UnityVersion version)
        {
            if (version >= new UnityVersion(6000, 6, 0, UnityVersionType.Beta, 1))
            {
                ClassStructHandler = NativeClassStructHandler_108_0.Instance;
            }
            else if (version >= new UnityVersion(6000, 5, 0, UnityVersionType.Alpha, 5))
            {
                ClassStructHandler = NativeClassStructHandler_105_0.Instance;
            }
            else if (version >= new UnityVersion(6000, 5, 0, UnityVersionType.Alpha, 0))
            {
                ClassStructHandler = NativeClassStructHandler_104_0.Instance;
            }
            else if (version >= new UnityVersion(6000, 4, 0, UnityVersionType.Beta, 8))
            {
                ClassStructHandler = NativeClassStructHandler_39_0.Instance;
            }
            else if (version >= new UnityVersion(6000, 4, 0, UnityVersionType.Alpha, 0))
            {
                ClassStructHandler = NativeClassStructHandler_29_2.Instance;
            }
            else if (version >= new UnityVersion(6000, 3, 3, UnityVersionType.Alpha, 0))
            {
                ClassStructHandler = NativeClassStructHandler_39_0.Instance;
            }
            else if (version >= new UnityVersion(2023, 1, 0, UnityVersionType.Alpha, 15))
            {
                ClassStructHandler = NativeClassStructHandler_29_2.Instance;
            }
            else if (version >= new UnityVersion(2022, 2, 0, UnityVersionType.Alpha, 0))
            {
                ClassStructHandler = NativeClassStructHandler_29_1.Instance;
            }
            else if (version >= new UnityVersion(2022, 1, 0, UnityVersionType.Alpha, 10))
            {
                ClassStructHandler = NativeClassStructHandler_29_0.Instance;
            }
            else if (version >= new UnityVersion(2022, 1, 0, UnityVersionType.Alpha, 0))
            {
                ClassStructHandler = NativeClassStructHandler_27_5.Instance;
            }
            else if (version >= new UnityVersion(2021, 2, 0, UnityVersionType.Beta, 13))
            {
                ClassStructHandler = NativeClassStructHandler_29_0.Instance;
            }
            else if (version >= new UnityVersion(2021, 2, 0, UnityVersionType.Alpha, 21))
            {
                ClassStructHandler = NativeClassStructHandler_27_5.Instance;
            }
            else if (version >= new UnityVersion(2021, 2, 0, UnityVersionType.Alpha, 12))
            {
                ClassStructHandler = NativeClassStructHandler_27_4.Instance;
            }
            else if (version >= new UnityVersion(2021, 2, 0, UnityVersionType.Alpha, 0))
            {
                ClassStructHandler = NativeClassStructHandler_27_3.Instance;
            }
            else if (version >= new UnityVersion(2021, 1, 24, UnityVersionType.Alpha, 0))
            {
                ClassStructHandler = NativeClassStructHandler_27_2.Instance;
            }
            else if (version >= new UnityVersion(2021, 1, 0, UnityVersionType.Alpha, 0))
            {
                ClassStructHandler = NativeClassStructHandler_27_1.Instance;
            }
            else if (version >= new UnityVersion(2020, 3, 20, UnityVersionType.Alpha, 0))
            {
                ClassStructHandler = NativeClassStructHandler_27_0.Instance;
            }
            else if (version >= new UnityVersion(2020, 2, 0, UnityVersionType.Alpha, 0))
            {
                ClassStructHandler = NativeClassStructHandler_24_7.Instance;
            }
            else if (version >= new UnityVersion(2019, 2, 0, UnityVersionType.Alpha, 6))
            {
                ClassStructHandler = NativeClassStructHandler_24_6.Instance;
            }
            else if (version >= new UnityVersion(2019, 2, 0, UnityVersionType.Alpha, 0))
            {
                ClassStructHandler = NativeClassStructHandler_24_5.Instance;
            }
            else if (version >= new UnityVersion(2019, 1, 0, UnityVersionType.Beta, 5))
            {
                ClassStructHandler = NativeClassStructHandler_24_6.Instance;
            }
            else if (version >= new UnityVersion(2019, 1, 0, UnityVersionType.Alpha, 11))
            {
                ClassStructHandler = NativeClassStructHandler_24_5.Instance;
            }
            else if (version >= new UnityVersion(2019, 1, 0, UnityVersionType.Alpha, 8))
            {
                ClassStructHandler = NativeClassStructHandler_24_3.Instance;
            }
            else if (version >= new UnityVersion(2019, 1, 0, UnityVersionType.Alpha, 0))
            {
                ClassStructHandler = NativeClassStructHandler_24_2.Instance;
            }
            else if (version >= new UnityVersion(2018, 3, 8, UnityVersionType.Alpha, 0))
            {
                ClassStructHandler = NativeClassStructHandler_24_4.Instance;
            }
            else if (version >= new UnityVersion(2018, 3, 0, UnityVersionType.Beta, 11))
            {
                ClassStructHandler = NativeClassStructHandler_24_3.Instance;
            }
            else if (version >= new UnityVersion(2018, 3, 0, UnityVersionType.Alpha, 0))
            {
                ClassStructHandler = NativeClassStructHandler_24_2.Instance;
            }
            else if (version >= new UnityVersion(2018, 2, 0, UnityVersionType.Alpha, 0))
            {
                ClassStructHandler = NativeClassStructHandler_24_1.Instance;
            }
            else if (version >= new UnityVersion(2018, 1, 0, UnityVersionType.Beta, 5))
            {
                ClassStructHandler = NativeClassStructHandler_24_0.Instance;
            }
            else if (version >= new UnityVersion(5, 6, 0, UnityVersionType.Beta, 3))
            {
                ClassStructHandler = NativeClassStructHandler_23_1.Instance;
            }
            else if (version >= new UnityVersion(5, 6, 0, UnityVersionType.Alpha, 0))
            {
                ClassStructHandler = NativeClassStructHandler_23_0.Instance;
            }
            else if (version >= new UnityVersion(5, 5, 0, UnityVersionType.Patch, 2))
            {
                ClassStructHandler = NativeClassStructHandler_22_1.Instance;
            }
            else if (version >= new UnityVersion(5, 5, 0, UnityVersionType.Alpha, 0))
            {
                ClassStructHandler = NativeClassStructHandler_22_0.Instance;
            }
            else if (version >= new UnityVersion(5, 4, 3, UnityVersionType.Patch, 4))
            {
                ClassStructHandler = NativeClassStructHandler_21_2.Instance;
            }
            else if (version >= new UnityVersion(5, 4, 0, UnityVersionType.Beta, 22))
            {
                ClassStructHandler = NativeClassStructHandler_21_1.Instance;
            }
            else if (version >= new UnityVersion(5, 4, 0, UnityVersionType.Beta, 19))
            {
                ClassStructHandler = NativeClassStructHandler_21_0.Instance;
            }
            else if (version >= new UnityVersion(5, 4, 0, UnityVersionType.Beta, 8))
            {
                ClassStructHandler = NativeClassStructHandler_20_0.Instance;
            }
            else if (version >= new UnityVersion(5, 4, 0, UnityVersionType.Beta, 3))
            {
                ClassStructHandler = NativeClassStructHandler_19_0.Instance;
            }
            else if (version >= new UnityVersion(5, 4, 0, UnityVersionType.Alpha, 0))
            {
                ClassStructHandler = NativeClassStructHandler_16_0.Instance;
            }
            else if (version >= new UnityVersion(5, 3, 5, UnityVersionType.Patch, 3))
            {
                ClassStructHandler = NativeClassStructHandler_21_1.Instance;
            }
            else if (version >= new UnityVersion(5, 3, 5, UnityVersionType.Patch, 1))
            {
                ClassStructHandler = NativeClassStructHandler_21_0.Instance;
            }
            else if (version >= new UnityVersion(5, 3, 2, UnityVersionType.Patch, 2))
            {
                ClassStructHandler = NativeClassStructHandler_20_0.Instance;
            }
            else if (version >= new UnityVersion(5, 3, 1, UnityVersionType.Patch, 3))
            {
                ClassStructHandler = NativeClassStructHandler_19_0.Instance;
            }
            else
            {
                ClassStructHandler = NativeClassStructHandler_16_0.Instance;
            }
        }
        private static INativeClassStructHandler ClassStructHandler { get; set; } = NativeClassStructHandler_16_0.Instance;
    }
}
