// <auto-generated />
using System.Runtime.InteropServices;
namespace Il2CppInterop.Runtime.Structs.VersionSpecific.Image
{
    [ApplicableToUnityVersionsSince("2018.1.0")]
    public unsafe class NativeImageStructHandler_24_2 : INativeImageStructHandler
    {
        private NativeImageStructHandler_24_2()
        {
        }
        public INativeImageStruct CreateNewStruct()
        {
            nint ptr = Marshal.AllocHGlobal(Size);
            Il2CppImage_24_2* _ = (Il2CppImage_24_2*)ptr;
            *_ = default;
            return new NativeStructWrapper(ptr);
        }
        public INativeImageStruct Wrap(Il2CppImage* ptr)
        {
            if (ptr == null) return null;
            return new NativeStructWrapper((nint)ptr);
        }
        public static NativeImageStructHandler_24_2 Instance { get; } = new();
        public int Size => sizeof(Il2CppImage_24_2);
        internal unsafe struct Il2CppImage_24_2
        {
            public byte* name;
            public byte* nameNoExt;
            public Il2CppAssembly* assembly;
            public int typeStart;
            public uint typeCount;
            public int exportedTypeStart;
            public uint exportedTypeCount;
            public int entryPointIndex;
            public void* nameToClassHashTable;
            public uint token;
        }
        internal class NativeStructWrapper : INativeImageStruct
        {
            public NativeStructWrapper(nint ptr) => Pointer = ptr;
            private byte _dynamicDummy;
            public nint Pointer { get; }
            private Il2CppImage_24_2* _ => (Il2CppImage_24_2*)Pointer;
            public Il2CppImage* ImagePointer => (Il2CppImage*)Pointer;
            public bool HasNameNoExt => true;
            public ref Il2CppAssembly* Assembly => ref _->assembly;
            public ref byte Dynamic => ref _dynamicDummy;
            public ref nint Name => ref *(nint*)&_->name;
            public ref nint NameNoExt => ref *(nint*)&_->nameNoExt;
        }
    }
}
