// <auto-generated />
using System.Runtime.InteropServices;
namespace Il2CppInterop.Runtime.Structs.VersionSpecific.Image
{
    [ApplicableToUnityVersionsSince("2017.1.0")]
    [ApplicableToUnityVersionsSince("2017.2.0")]
    public unsafe class NativeImageStructHandler_24_0 : INativeImageStructHandler
    {
        private NativeImageStructHandler_24_0()
        {
        }
        public INativeImageStruct CreateNewStruct()
        {
            nint ptr = Marshal.AllocHGlobal(Size);
            Il2CppImage_24_0* _ = (Il2CppImage_24_0*)ptr;
            *_ = default;
            return new NativeStructWrapper(ptr);
        }
        public INativeImageStruct Wrap(Il2CppImage* ptr)
        {
            if (ptr == null) return null;
            return new NativeStructWrapper((nint)ptr);
        }
        public static NativeImageStructHandler_24_0 Instance { get; } = new();
        public int Size => sizeof(Il2CppImage_24_0);
        internal unsafe struct Il2CppImage_24_0
        {
            public byte* name;
            public int assemblyIndex;
            public int typeStart;
            public uint typeCount;
            public int exportedTypeStart;
            public uint exportedTypeCount;
            public int entryPointIndex;
            public void* nameToClassHashTable;
            public uint token;
        }
        internal class NativeStructWrapper : INativeImageStruct
        {
            public NativeStructWrapper(nint ptr) => Pointer = ptr;
            private byte _dynamicDummy;
            public nint Pointer { get; }
            private Il2CppImage_24_0* _ => (Il2CppImage_24_0*)Pointer;
            public Il2CppImage* ImagePointer => (Il2CppImage*)Pointer;
            public bool HasNameNoExt => false;
            public ref Il2CppAssembly* Assembly => throw new System.NotSupportedException();
            public ref byte Dynamic => ref _dynamicDummy;
            public ref nint Name => ref *(nint*)&_->name;
            public ref nint NameNoExt => throw new System.NotSupportedException();
        }
    }
}
