// <auto-generated />
using System.Runtime.InteropServices;
namespace Il2CppInterop.Runtime.Structs.VersionSpecific.Image
{
    [ApplicableToUnityVersionsSince("2019.1.0a12")]
    public unsafe class NativeImageStructHandler_24_5 : INativeImageStructHandler
    {
        private NativeImageStructHandler_24_5()
        {
        }
        public INativeImageStruct CreateNewStruct()
        {
            nint ptr = Marshal.AllocHGlobal(Size);
            Il2CppImage_24_5* _ = (Il2CppImage_24_5*)ptr;
            *_ = default;
            return new NativeStructWrapper(ptr);
        }
        public INativeImageStruct Wrap(Il2CppImage* ptr)
        {
            if (ptr == null) return null;
            return new NativeStructWrapper((nint)ptr);
        }
        public static NativeImageStructHandler_24_5 Instance { get; } = new();
        public int Size => sizeof(Il2CppImage_24_5);
        internal unsafe struct Il2CppImage_24_5
        {
            public byte* name;
            public byte* nameNoExt;
            public Il2CppAssembly* assembly;
            public int typeStart;
            public uint typeCount;
            public int exportedTypeStart;
            public uint exportedTypeCount;
            public int customAttributeStart;
            public uint customAttributeCount;
            public int entryPointIndex;
            public void* nameToClassHashTable;
            public void* codeGenModule;
            public uint token;
            public byte dynamic;
        }
        internal class NativeStructWrapper : INativeImageStruct
        {
            public NativeStructWrapper(nint ptr) => Pointer = ptr;
            public nint Pointer { get; }
            private Il2CppImage_24_5* _ => (Il2CppImage_24_5*)Pointer;
            public Il2CppImage* ImagePointer => (Il2CppImage*)Pointer;
            public bool HasNameNoExt => true;
            public ref Il2CppAssembly* Assembly => ref _->assembly;
            public ref byte Dynamic => ref _->dynamic;
            public ref nint Name => ref *(nint*)&_->name;
            public ref nint NameNoExt => ref *(nint*)&_->nameNoExt;
        }
    }
}
