// <auto-generated />
using System.Runtime.InteropServices;
namespace Il2CppInterop.Runtime.Structs.VersionSpecific.Image
{
    [ApplicableToUnityVersionsSince("2020.2.0")]
    public unsafe class NativeImageStructHandler_24_6 : INativeImageStructHandler
    {
        private NativeImageStructHandler_24_6()
        {
        }
        public INativeImageStruct CreateNewStruct()
        {
            nint ptr = Marshal.AllocHGlobal(Size);
            Il2CppImage_24_6* _ = (Il2CppImage_24_6*)ptr;
            *_ = default;
            Il2CppImageGlobalMetadata* metadata = (Il2CppImageGlobalMetadata*)Marshal.AllocHGlobal(sizeof(Il2CppImageGlobalMetadata));
            metadata->image = (Il2CppImage*)_;
            *(Il2CppImageGlobalMetadata**)&_->metadataHandle = metadata;
            return new NativeStructWrapper(ptr);
        }
        public INativeImageStruct Wrap(Il2CppImage* ptr)
        {
            if (ptr == null) return null;
            return new NativeStructWrapper((nint)ptr);
        }
        public static NativeImageStructHandler_24_6 Instance { get; } = new();
        public int Size => sizeof(Il2CppImage_24_6);
        internal unsafe struct Il2CppImage_24_6
        {
            public byte* name;
            public byte* nameNoExt;
            public Il2CppAssembly* assembly;
            public uint typeCount;
            public uint exportedTypeCount;
            public uint customAttributeCount;
            public Il2CppMetadataImageHandle metadataHandle;
            public void* nameToClassHashTable;
            public void* codeGenModule;
            public uint token;
            public byte dynamic;
        }
        internal class NativeStructWrapper : INativeImageStruct
        {
            public NativeStructWrapper(nint ptr) => Pointer = ptr;
            public nint Pointer { get; }
            private Il2CppImage_24_6* _ => (Il2CppImage_24_6*)Pointer;
            public Il2CppImage* ImagePointer => (Il2CppImage*)Pointer;
            public bool HasNameNoExt => true;
            public ref Il2CppAssembly* Assembly => ref _->assembly;
            public ref byte Dynamic => ref _->dynamic;
            public ref nint Name => ref *(nint*)&_->name;
            public ref nint NameNoExt => ref *(nint*)&_->nameNoExt;
        }
    }
}
