// <auto-generated />
namespace Il2CppInterop.Runtime.Structs.VersionSpecific.Image
{
    public interface INativeImageStructHandler : INativeStructHandler
    {
        INativeImageStruct CreateNewStruct();
        unsafe INativeImageStruct Wrap(Il2CppImage* pointer);
    }
    public interface INativeImageStruct : INativeStruct
    {
        unsafe Il2CppImage* ImagePointer { get; }
        bool HasNameNoExt { get; }
        unsafe ref Il2CppAssembly* Assembly { get; }
        ref byte Dynamic { get; }
        ref nint Name { get; }
        ref nint NameNoExt { get; }
    }
}
