// <auto-generated />
using AssetRipper.Primitives;
using Il2CppInterop.Runtime.Structs.VersionSpecific.Image;
namespace Il2CppInterop.Runtime.Structs
{
    public static partial class UnityVersionHandler
    {
        private static void SetImageStructHandler(UnityVersion version)
        {
            if (version >= new UnityVersion(2020, 2, 0, UnityVersionType.Alpha, 0))
            {
                ImageStructHandler = NativeImageStructHandler_24_6.Instance;
            }
            else if (version >= new UnityVersion(2019, 1, 0, UnityVersionType.Alpha, 12))
            {
                ImageStructHandler = NativeImageStructHandler_24_5.Instance;
            }
            else if (version >= new UnityVersion(2018, 3, 0, UnityVersionType.Alpha, 0))
            {
                ImageStructHandler = NativeImageStructHandler_24_4.Instance;
            }
            else if (version >= new UnityVersion(2018, 1, 0, UnityVersionType.Beta, 5))
            {
                ImageStructHandler = NativeImageStructHandler_24_3.Instance;
            }
            else if (version >= new UnityVersion(2018, 1, 0, UnityVersionType.Alpha, 0))
            {
                ImageStructHandler = NativeImageStructHandler_24_2.Instance;
            }
            else if (version >= new UnityVersion(2017, 2, 0, UnityVersionType.Patch, 2))
            {
                ImageStructHandler = NativeImageStructHandler_24_1.Instance;
            }
            else if (version >= new UnityVersion(2017, 2, 0, UnityVersionType.Alpha, 0))
            {
                ImageStructHandler = NativeImageStructHandler_24_0.Instance;
            }
            else if (version >= new UnityVersion(2017, 1, 2, UnityVersionType.Patch, 1))
            {
                ImageStructHandler = NativeImageStructHandler_24_1.Instance;
            }
            else if (version >= new UnityVersion(2017, 1, 0, UnityVersionType.Alpha, 0))
            {
                ImageStructHandler = NativeImageStructHandler_24_0.Instance;
            }
            else if (version >= new UnityVersion(5, 4, 0, UnityVersionType.Beta, 3))
            {
                ImageStructHandler = NativeImageStructHandler_19_0.Instance;
            }
            else if (version >= new UnityVersion(5, 4, 0, UnityVersionType.Alpha, 0))
            {
                ImageStructHandler = NativeImageStructHandler_16_0.Instance;
            }
            else if (version >= new UnityVersion(5, 3, 1, UnityVersionType.Patch, 3))
            {
                ImageStructHandler = NativeImageStructHandler_19_0.Instance;
            }
            else
            {
                ImageStructHandler = NativeImageStructHandler_16_0.Instance;
            }
        }
        private static INativeImageStructHandler ImageStructHandler { get; set; } = NativeImageStructHandler_16_0.Instance;
    }
}
