using System.CodeDom.Compiler;

namespace Il2CppInterop.StructGenerator.CodeGen;

internal class CodeGenFile
{
    public string? Namespace { get; set; }
    public List<CodeGenElement> Elements { get; } = [];
    public List<string> Usings { get; } = [];

    private void Build(IndentedTextWriter writer)
    {
        writer.WriteLine("// <auto-generated />");
        foreach (var @using in Usings)
            writer.WriteUsing(@using);
        if (Namespace != null)
        {
            writer.WriteLine($"namespace {Namespace}");
            writer.WriteLine("{");
            writer.Indent++;
        }
        foreach (var element in Elements)
            element.Build(writer);
        if (Namespace != null)
        {
            writer.Indent--;
            writer.WriteLine("}");
        }
    }

    public void WriteTo(string path)
    {
        using StreamWriter writer = new(path)
        {
            NewLine = "\n"
        };
        using IndentedTextWriter indentedWriter = new(writer);
        Build(indentedWriter);
    }
}
