namespace Il2CppInterop.SourceGenerator.Tests.Generation;

public class InjectedClassTests : SourceGenerationTests
{
    [Test]
    public Task ClassWithNoMembers()
    {
        var testCode = """
            using Il2CppInterop.Common.Attributes;

            [InjectedType]
            public partial class Sample : Il2CppSystem.Object
            {
            }
            """;

        var expectedGeneratedCode = """
            // <auto-generated/>
            #nullable enable

            [global::Il2CppInterop.Common.Attributes.Il2CppType(typeof(Il2CppInternals))]
            public partial class Sample : global::Il2CppInterop.Common.IIl2CppType<Sample>
            {
                public Sample(global::Il2CppInterop.Common.ObjectPointer pointer) : base(pointer)
                {
                }

                nint global::Il2CppInterop.Common.IIl2CppType.ObjectClass => global::Il2CppInterop.Common.Il2CppType.GetClassPointer<Sample>();
            
                static Sample global::Il2CppInterop.Common.IIl2CppType<Sample>.UnboxNative(global::Il2CppInterop.Common.ObjectPointer pointer) => new Sample(pointer);

                static int global::Il2CppInterop.Common.IIl2CppType<Sample>.Size => nint.Size;
            
                static Sample? global::Il2CppInterop.Common.IIl2CppType<Sample>.ReadFromSpan(global::System.ReadOnlySpan<byte> span)
                {
                    return global::Il2CppInterop.Common.Il2CppType.ReadReference<Sample>(span);
                }

                static void global::Il2CppInterop.Common.IIl2CppType<Sample>.WriteToSpan(Sample? value, global::System.Span<byte> span)
                {
                    global::Il2CppInterop.Common.Il2CppType.WriteReference(value, span);
                }
            
                static Sample()
                {
                    global::System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(typeof(Il2CppInternals).TypeHandle);
                }
            }

            file static class Il2CppInternals
            {
            
                static Il2CppInternals()
                {
            #pragma warning disable IL2026 // Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code
            #pragma warning disable IL3050 // Calling members annotated with 'RequiresDynamicCodeAttribute' may break functionality when AOT compiling.
                    global::Il2CppInterop.Runtime.Injection.TypeInjector.RegisterTypeInIl2Cpp<Sample>();
            #pragma warning restore IL3050 // Calling members annotated with 'RequiresDynamicCodeAttribute' may break functionality when AOT compiling.
            #pragma warning restore IL2026 // Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code
                }
            }

            """;

        return TestGeneration(testCode, "Sample.g.cs", expectedGeneratedCode);
    }
}
