namespace Il2CppInterop.SourceGenerator.Tests.Generation;

public class InjectedStructTests : SourceGenerationTests
{
    [Test]
    public Task StructWithNoMembers()
    {
        var testCode = """
            using Il2CppInterop.Common.Attributes;

            [InjectedType]
            public partial struct Sample
            {
            }
            """;

        var expectedGeneratedCode = """
            // <auto-generated/>
            #nullable enable

            [global::Il2CppInterop.Common.Attributes.Il2CppType(typeof(Il2CppInternals))]
            public partial struct Sample :
                global::Il2CppSystem.IValueType,
                global::Il2CppInterop.Common.IIl2CppType<Sample>
            {
                [global::Il2CppInterop.Common.Attributes.Il2CppMethod]
                public global::Il2CppSystem.Boolean Equals(global::Il2CppSystem.IObject obj)
                {
                    return this.Equals((object)obj);
                }

                [global::Il2CppInterop.Common.Attributes.Il2CppMethod(Name = "GetHashCode")]
                public global::Il2CppSystem.Int32 GetIl2CppHashCode()
                {
                    return this.GetHashCode();
                }

                [global::Il2CppInterop.Common.Attributes.Il2CppMethod(Name = "ToString")]
                public global::Il2CppSystem.String ToIl2CppString()
                {
                    return this.ToString();
                }

                nint global::Il2CppInterop.Common.IIl2CppType.ObjectClass => global::Il2CppInterop.Common.Il2CppType.GetClassPointer<Sample>();

                readonly global::Il2CppInterop.Common.ObjectPointer global::Il2CppInterop.Common.IIl2CppType.BoxNative() => global::Il2CppInterop.Runtime.NativeBoxing.BoxValueType<Sample>(in this);

                static int global::Il2CppInterop.Common.IIl2CppType<Sample>.Size => Il2CppInternals.Size;

                static Sample global::Il2CppInterop.Common.IIl2CppType<Sample>.ReadFromSpan(global::System.ReadOnlySpan<byte> span)
                {
                    #nullable disable
                    return new Sample
                    {
                    };
                    #nullable restore
                }

                static void global::Il2CppInterop.Common.IIl2CppType<Sample>.WriteToSpan(Sample value, global::System.Span<byte> span)
                {
                }

                static Sample()
                {
                    global::System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(typeof(Il2CppInternals).TypeHandle);
                }
            }

            file static class Il2CppInternals
            {
                public static readonly int Size;

                static Il2CppInternals()
                {
            #pragma warning disable IL2026 // Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code
            #pragma warning disable IL3050 // Calling members annotated with 'RequiresDynamicCodeAttribute' may break functionality when AOT compiling.
                    global::Il2CppInterop.Runtime.Injection.TypeInjector.RegisterTypeInIl2Cpp<Sample>();
            #pragma warning restore IL3050 // Calling members annotated with 'RequiresDynamicCodeAttribute' may break functionality when AOT compiling.
            #pragma warning restore IL2026 // Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code
                    Size = global::Il2CppInterop.Common.IL2CPP.il2cpp_class_value_size(global::Il2CppInterop.Common.Il2CppType.GetClassPointer<Sample>(), out _);
                }
            }

            """;

        return TestGeneration(testCode, "Sample.g.cs", expectedGeneratedCode);
    }

    [Test]
    public Task StructContainingPrimitiveFieldsWithAttributes()
    {
        var testCode = """
            using Il2CppInterop.Common.Attributes;

            [InjectedType]
            public partial struct Sample
            {
                [Il2CppField]
                public Il2CppSystem.Int32 intValue;
                [Il2CppField]
                public Il2CppSystem.String stringValue;
            }
            """;

        var expectedGeneratedCode = """
            // <auto-generated/>
            #nullable enable

            [global::Il2CppInterop.Common.Attributes.Il2CppType(typeof(Il2CppInternals))]
            public partial struct Sample :
                global::Il2CppSystem.IValueType,
                global::Il2CppInterop.Common.IIl2CppType<Sample>
            {
                [global::Il2CppInterop.Common.Attributes.Il2CppMethod]
                public global::Il2CppSystem.Boolean Equals(global::Il2CppSystem.IObject obj)
                {
                    return this.Equals((object)obj);
                }

                [global::Il2CppInterop.Common.Attributes.Il2CppMethod(Name = "GetHashCode")]
                public global::Il2CppSystem.Int32 GetIl2CppHashCode()
                {
                    return this.GetHashCode();
                }

                [global::Il2CppInterop.Common.Attributes.Il2CppMethod(Name = "ToString")]
                public global::Il2CppSystem.String ToIl2CppString()
                {
                    return this.ToString();
                }

                nint global::Il2CppInterop.Common.IIl2CppType.ObjectClass => global::Il2CppInterop.Common.Il2CppType.GetClassPointer<Sample>();

                readonly global::Il2CppInterop.Common.ObjectPointer global::Il2CppInterop.Common.IIl2CppType.BoxNative() => global::Il2CppInterop.Runtime.NativeBoxing.BoxValueType<Sample>(in this);

                static int global::Il2CppInterop.Common.IIl2CppType<Sample>.Size => Il2CppInternals.Size;

                static Sample global::Il2CppInterop.Common.IIl2CppType<Sample>.ReadFromSpan(global::System.ReadOnlySpan<byte> span)
                {
                    #nullable disable
                    return new Sample
                    {
                        intValue = global::Il2CppInterop.Common.Il2CppType.ReadFromSpanAtOffset<global::Il2CppSystem.Int32>(span, Il2CppInternals.FieldOffset_0),
                        stringValue = global::Il2CppInterop.Common.Il2CppType.ReadFromSpanAtOffset<global::Il2CppSystem.String>(span, Il2CppInternals.FieldOffset_1),
                    };
                    #nullable restore
                }

                static void global::Il2CppInterop.Common.IIl2CppType<Sample>.WriteToSpan(Sample value, global::System.Span<byte> span)
                {
                    global::Il2CppInterop.Common.Il2CppType.WriteToSpanAtOffset(value.intValue, span, Il2CppInternals.FieldOffset_0);
                    global::Il2CppInterop.Common.Il2CppType.WriteToSpanAtOffset(value.stringValue, span, Il2CppInternals.FieldOffset_1);
                }

                static Sample()
                {
                    global::System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(typeof(Il2CppInternals).TypeHandle);
                }
            }

            file static class Il2CppInternals
            {
                public static readonly int Size;
                public static readonly int FieldOffset_0; // intValue
                public static readonly int FieldOffset_1; // stringValue

                static Il2CppInternals()
                {
            #pragma warning disable IL2026 // Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code
            #pragma warning disable IL3050 // Calling members annotated with 'RequiresDynamicCodeAttribute' may break functionality when AOT compiling.
                    global::Il2CppInterop.Runtime.Injection.TypeInjector.RegisterTypeInIl2Cpp<Sample>();
            #pragma warning restore IL3050 // Calling members annotated with 'RequiresDynamicCodeAttribute' may break functionality when AOT compiling.
            #pragma warning restore IL2026 // Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code
                    Size = global::Il2CppInterop.Common.IL2CPP.il2cpp_class_value_size(global::Il2CppInterop.Common.Il2CppType.GetClassPointer<Sample>(), out _);
                    FieldOffset_0 = global::Il2CppInterop.Runtime.FieldAccess.GetFieldOffset(global::Il2CppInterop.Runtime.FieldAccess.GetFieldInfo(global::Il2CppInterop.Common.Il2CppType.GetClassPointer<Sample>(), "intValue"));
                    FieldOffset_1 = global::Il2CppInterop.Runtime.FieldAccess.GetFieldOffset(global::Il2CppInterop.Runtime.FieldAccess.GetFieldInfo(global::Il2CppInterop.Common.Il2CppType.GetClassPointer<Sample>(), "stringValue"));
                }
            }

            """;

        return TestGeneration(testCode, "Sample.g.cs", expectedGeneratedCode);
    }

    [Test]
    public Task StructContainingPrimitiveFieldsWithoutAttributes()
    {
        // Il2CppField attributes are optional for instance struct fields
        var testCode = """
            using Il2CppInterop.Common.Attributes;

            [InjectedType]
            public partial struct Sample
            {
                public Il2CppSystem.Int32 intValue;
                public Il2CppSystem.String stringValue;
            }
            """;

        var expectedGeneratedCode = """
            // <auto-generated/>
            #nullable enable

            [global::Il2CppInterop.Common.Attributes.Il2CppType(typeof(Il2CppInternals))]
            public partial struct Sample :
                global::Il2CppSystem.IValueType,
                global::Il2CppInterop.Common.IIl2CppType<Sample>
            {
                [global::Il2CppInterop.Common.Attributes.Il2CppMethod]
                public global::Il2CppSystem.Boolean Equals(global::Il2CppSystem.IObject obj)
                {
                    return this.Equals((object)obj);
                }

                [global::Il2CppInterop.Common.Attributes.Il2CppMethod(Name = "GetHashCode")]
                public global::Il2CppSystem.Int32 GetIl2CppHashCode()
                {
                    return this.GetHashCode();
                }

                [global::Il2CppInterop.Common.Attributes.Il2CppMethod(Name = "ToString")]
                public global::Il2CppSystem.String ToIl2CppString()
                {
                    return this.ToString();
                }

                nint global::Il2CppInterop.Common.IIl2CppType.ObjectClass => global::Il2CppInterop.Common.Il2CppType.GetClassPointer<Sample>();

                readonly global::Il2CppInterop.Common.ObjectPointer global::Il2CppInterop.Common.IIl2CppType.BoxNative() => global::Il2CppInterop.Runtime.NativeBoxing.BoxValueType<Sample>(in this);

                static int global::Il2CppInterop.Common.IIl2CppType<Sample>.Size => Il2CppInternals.Size;

                static Sample global::Il2CppInterop.Common.IIl2CppType<Sample>.ReadFromSpan(global::System.ReadOnlySpan<byte> span)
                {
                    #nullable disable
                    return new Sample
                    {
                        intValue = global::Il2CppInterop.Common.Il2CppType.ReadFromSpanAtOffset<global::Il2CppSystem.Int32>(span, Il2CppInternals.FieldOffset_0),
                        stringValue = global::Il2CppInterop.Common.Il2CppType.ReadFromSpanAtOffset<global::Il2CppSystem.String>(span, Il2CppInternals.FieldOffset_1),
                    };
                    #nullable restore
                }

                static void global::Il2CppInterop.Common.IIl2CppType<Sample>.WriteToSpan(Sample value, global::System.Span<byte> span)
                {
                    global::Il2CppInterop.Common.Il2CppType.WriteToSpanAtOffset(value.intValue, span, Il2CppInternals.FieldOffset_0);
                    global::Il2CppInterop.Common.Il2CppType.WriteToSpanAtOffset(value.stringValue, span, Il2CppInternals.FieldOffset_1);
                }

                static Sample()
                {
                    global::System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(typeof(Il2CppInternals).TypeHandle);
                }
            }

            file static class Il2CppInternals
            {
                public static readonly int Size;
                public static readonly int FieldOffset_0; // intValue
                public static readonly int FieldOffset_1; // stringValue

                static Il2CppInternals()
                {
            #pragma warning disable IL2026 // Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code
            #pragma warning disable IL3050 // Calling members annotated with 'RequiresDynamicCodeAttribute' may break functionality when AOT compiling.
                    global::Il2CppInterop.Runtime.Injection.TypeInjector.RegisterTypeInIl2Cpp<Sample>();
            #pragma warning restore IL3050 // Calling members annotated with 'RequiresDynamicCodeAttribute' may break functionality when AOT compiling.
            #pragma warning restore IL2026 // Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code
                    Size = global::Il2CppInterop.Common.IL2CPP.il2cpp_class_value_size(global::Il2CppInterop.Common.Il2CppType.GetClassPointer<Sample>(), out _);
                    FieldOffset_0 = global::Il2CppInterop.Runtime.FieldAccess.GetFieldOffset(global::Il2CppInterop.Runtime.FieldAccess.GetFieldInfo(global::Il2CppInterop.Common.Il2CppType.GetClassPointer<Sample>(), "intValue"));
                    FieldOffset_1 = global::Il2CppInterop.Runtime.FieldAccess.GetFieldOffset(global::Il2CppInterop.Runtime.FieldAccess.GetFieldInfo(global::Il2CppInterop.Common.Il2CppType.GetClassPointer<Sample>(), "stringValue"));
                }
            }

            """;

        return TestGeneration(testCode, "Sample.g.cs", expectedGeneratedCode);
    }
}
