// <auto-generated />
using System.Runtime.InteropServices;
namespace Il2CppInterop.Runtime.Structs.VersionSpecific.Exception
{
    [ApplicableToUnityVersionsSince("5.6.0b6")]
    public unsafe class NativeExceptionStructHandler_23_1 : INativeExceptionStructHandler
    {
        private NativeExceptionStructHandler_23_1()
        {
        }
        public INativeExceptionStruct CreateNewStruct()
        {
            nint ptr = Marshal.AllocHGlobal(Size);
            Il2CppException_23_1* _ = (Il2CppException_23_1*)ptr;
            *_ = default;
            return new NativeStructWrapper(ptr);
        }
        public INativeExceptionStruct Wrap(Il2CppException* ptr)
        {
            if (ptr == null) return null;
            return new NativeStructWrapper((nint)ptr);
        }
        public static NativeExceptionStructHandler_23_1 Instance { get; } = new();
        public int Size => sizeof(Il2CppException_23_1);
        internal unsafe struct Il2CppException_23_1
        {
            public Il2CppObject Object;
            public Il2CppString* className;
            public Il2CppString* message;
            public Il2CppObject* _data;
            public Il2CppException* inner_ex;
            public Il2CppString* _helpURL;
            public void* trace_ips;
            public Il2CppString* stack_trace;
            public Il2CppString* remote_stack_trace;
            public int remote_stack_index;
            public Il2CppObject* _dynamicMethods;
            public il2cpp_hresult_t hresult;
            public Il2CppString* source;
            public Il2CppObject* safeSerializationManager;
            public void* captured_traces;
            public void* native_trace_ips;
        }
        internal class NativeStructWrapper : INativeExceptionStruct
        {
            public NativeStructWrapper(nint ptr) => Pointer = ptr;
            public nint Pointer { get; }
            private Il2CppException_23_1* _ => (Il2CppException_23_1*)Pointer;
            public Il2CppException* ExceptionPointer => (Il2CppException*)Pointer;
            public ref Il2CppException* InnerException => ref _->inner_ex;
            public ref Il2CppString* Message => ref _->message;
            public ref Il2CppString* HelpLink => ref _->_helpURL;
            public ref Il2CppString* ClassName => ref _->className;
            public ref Il2CppString* StackTrace => ref _->stack_trace;
            public ref Il2CppString* RemoteStackTrace => ref _->remote_stack_trace;
        }
    }
}
