// <auto-generated />
using AssetRipper.Primitives;
using Il2CppInterop.Runtime.Structs.VersionSpecific.Exception;
namespace Il2CppInterop.Runtime.Structs
{
    public static partial class UnityVersionHandler
    {
        private static void SetExceptionStructHandler(UnityVersion version)
        {
            if (version >= new UnityVersion(2021, 2, 0, UnityVersionType.Alpha, 19))
            {
                ExceptionStructHandler = NativeExceptionStructHandler_27_0.Instance;
            }
            else if (version >= new UnityVersion(2018, 1, 0, UnityVersionType.Beta, 5))
            {
                ExceptionStructHandler = NativeExceptionStructHandler_23_0.Instance;
            }
            else if (version >= new UnityVersion(5, 6, 0, UnityVersionType.Beta, 6))
            {
                ExceptionStructHandler = NativeExceptionStructHandler_23_1.Instance;
            }
            else if (version >= new UnityVersion(5, 6, 0, UnityVersionType.Beta, 3))
            {
                ExceptionStructHandler = NativeExceptionStructHandler_23_0.Instance;
            }
            else if (version >= new UnityVersion(5, 5, 0, UnityVersionType.Alpha, 0))
            {
                ExceptionStructHandler = NativeExceptionStructHandler_22_0.Instance;
            }
            else if (version >= new UnityVersion(5, 4, 0, UnityVersionType.Beta, 15))
            {
                ExceptionStructHandler = NativeExceptionStructHandler_21_0.Instance;
            }
            else if (version >= new UnityVersion(5, 4, 0, UnityVersionType.Beta, 8))
            {
                ExceptionStructHandler = NativeExceptionStructHandler_20_0.Instance;
            }
            else if (version >= new UnityVersion(5, 4, 0, UnityVersionType.Alpha, 0))
            {
                ExceptionStructHandler = NativeExceptionStructHandler_16_0.Instance;
            }
            else if (version >= new UnityVersion(5, 3, 4, UnityVersionType.Patch, 3))
            {
                ExceptionStructHandler = NativeExceptionStructHandler_21_0.Instance;
            }
            else if (version >= new UnityVersion(5, 3, 2, UnityVersionType.Patch, 2))
            {
                ExceptionStructHandler = NativeExceptionStructHandler_20_0.Instance;
            }
            else
            {
                ExceptionStructHandler = NativeExceptionStructHandler_16_0.Instance;
            }
        }
        private static INativeExceptionStructHandler ExceptionStructHandler { get; set; } = NativeExceptionStructHandler_16_0.Instance;
    }
}
