// <auto-generated />
using AssetRipper.Primitives;
using Il2CppInterop.Runtime.Structs.VersionSpecific.Type;
namespace Il2CppInterop.Runtime.Structs
{
    public static partial class UnityVersionHandler
    {
        private static void SetTypeStructHandler(UnityVersion version)
        {
            if (version >= new UnityVersion(2021, 1, 0, UnityVersionType.Alpha, 0))
            {
                TypeStructHandler = NativeTypeStructHandler_27_0.Instance;
            }
            else
            {
                TypeStructHandler = NativeTypeStructHandler_16_0.Instance;
            }
        }
        private static INativeTypeStructHandler TypeStructHandler { get; set; } = NativeTypeStructHandler_16_0.Instance;
    }
}
