// <auto-generated />
using System.Runtime.InteropServices;
using Il2CppInterop.Runtime.Structs.VersionSpecific.AssemblyName;
namespace Il2CppInterop.Runtime.Structs.VersionSpecific.Assembly
{
    [ApplicableToUnityVersionsSince("6000.5.0")]
    public unsafe class NativeAssemblyStructHandler_104_0 : INativeAssemblyStructHandler
    {
        private NativeAssemblyStructHandler_104_0()
        {
        }
        public INativeAssemblyStruct CreateNewStruct()
        {
            nint ptr = Marshal.AllocHGlobal(Size);
            Il2CppAssembly_104_0* _ = (Il2CppAssembly_104_0*)ptr;
            *_ = default;
            return new NativeStructWrapper(ptr);
        }
        public INativeAssemblyStruct Wrap(Il2CppAssembly* ptr)
        {
            if (ptr == null) return null;
            return new NativeStructWrapper((nint)ptr);
        }
        public static NativeAssemblyStructHandler_104_0 Instance { get; } = new();
        public int Size => sizeof(Il2CppAssembly_104_0);
        internal unsafe struct Il2CppAssembly_104_0
        {
            public Il2CppImage* image;
            public uint token;
            public uint moduleToken;
            public int referencedAssemblyStart;
            public int referencedAssemblyCount;
            public NativeAssemblyNameStructHandler_24_1.Il2CppAssemblyName_24_1 aname;
        }
        internal class NativeStructWrapper : INativeAssemblyStruct
        {
            public NativeStructWrapper(nint ptr) => Pointer = ptr;
            public nint Pointer { get; }
            private Il2CppAssembly_104_0* _ => (Il2CppAssembly_104_0*)Pointer;
            public Il2CppAssembly* AssemblyPointer => (Il2CppAssembly*)Pointer;
            public INativeAssemblyNameStruct Name
            {
                get => UnityVersionHandler.Wrap((Il2CppAssemblyName*)&_->aname);
                set => _->aname = *(NativeAssemblyNameStructHandler_24_1.Il2CppAssemblyName_24_1*)Name.AssemblyNamePointer;
            }
            public ref Il2CppImage* Image => ref _->image;
        }
    }
}
