// <auto-generated />
using AssetRipper.Primitives;
using Il2CppInterop.Runtime.Structs.VersionSpecific.Assembly;
namespace Il2CppInterop.Runtime.Structs
{
    public static partial class UnityVersionHandler
    {
        private static void SetAssemblyStructHandler(UnityVersion version)
        {
            if (version >= new UnityVersion(6000, 5, 0, UnityVersionType.Alpha, 0))
            {
                AssemblyStructHandler = NativeAssemblyStructHandler_104_0.Instance;
            }
            else if (version >= new UnityVersion(2020, 2, 0, UnityVersionType.Beta, 7))
            {
                AssemblyStructHandler = NativeAssemblyStructHandler_24_2.Instance;
            }
            else if (version >= new UnityVersion(2020, 2, 0, UnityVersionType.Alpha, 0))
            {
                AssemblyStructHandler = NativeAssemblyStructHandler_24_1.Instance;
            }
            else if (version >= new UnityVersion(2020, 1, 11, UnityVersionType.Alpha, 0))
            {
                AssemblyStructHandler = NativeAssemblyStructHandler_24_2.Instance;
            }
            else if (version >= new UnityVersion(2020, 1, 0, UnityVersionType.Alpha, 0))
            {
                AssemblyStructHandler = NativeAssemblyStructHandler_24_1.Instance;
            }
            else if (version >= new UnityVersion(2019, 4, 15, UnityVersionType.Alpha, 0))
            {
                AssemblyStructHandler = NativeAssemblyStructHandler_24_2.Instance;
            }
            else if (version >= new UnityVersion(2019, 1, 0, UnityVersionType.Alpha, 0))
            {
                AssemblyStructHandler = NativeAssemblyStructHandler_24_1.Instance;
            }
            else if (version >= new UnityVersion(2018, 4, 34, UnityVersionType.Alpha, 0))
            {
                AssemblyStructHandler = NativeAssemblyStructHandler_24_2.Instance;
            }
            else if (version >= new UnityVersion(2018, 3, 0, UnityVersionType.Alpha, 0))
            {
                AssemblyStructHandler = NativeAssemblyStructHandler_24_1.Instance;
            }
            else if (version >= new UnityVersion(2018, 1, 0, UnityVersionType.Beta, 5))
            {
                AssemblyStructHandler = NativeAssemblyStructHandler_24_0.Instance;
            }
            else if (version >= new UnityVersion(5, 4, 0, UnityVersionType.Beta, 4))
            {
                AssemblyStructHandler = NativeAssemblyStructHandler_20_0.Instance;
            }
            else if (version >= new UnityVersion(5, 4, 0, UnityVersionType.Alpha, 0))
            {
                AssemblyStructHandler = NativeAssemblyStructHandler_16_0.Instance;
            }
            else if (version >= new UnityVersion(5, 3, 2, UnityVersionType.Patch, 1))
            {
                AssemblyStructHandler = NativeAssemblyStructHandler_20_0.Instance;
            }
            else
            {
                AssemblyStructHandler = NativeAssemblyStructHandler_16_0.Instance;
            }
        }
        private static INativeAssemblyStructHandler AssemblyStructHandler { get; set; } = NativeAssemblyStructHandler_16_0.Instance;
    }
}
